spring.application.name=granja-system

spring.data.mongodb.uri=mongodb+srv://SEU_USERNAME_AQUI:SUA_SENHA_AQUI@granja-cluster.ia8cm6i.mongodb.net/granja_db?appName=granja-cluster

spring.data.mongodb.database=granja_db